sudo: required
language: python
install:
    - pip install -r requirements.txt
script:
    - planemo test --conda_auto_init --conda_dependency_resolution --conda_auto_install --conda_ensure_channels scottx611x --conda_debug
after_success:
    - planemo shed_update --shed_target testtoolshed --shed_email $SHED_EMAIL --shed_password $SHED_PASSWORD
notifications:
    email:
        recipients:
            - scottx611x@gmail.com
    on_success: never