sudo: required
language: python
cache: pip
install:
    - pip install -r requirements.txt
script:
    - planemo test --conda_auto_init --conda_dependency_resolution --conda_auto_install --conda_ensure_channels scottx611x --no_cache_galaxy --no_cleanup  --test_output ./test.html
    - cat ./test.html
after_success:
    - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then planemo shed_update --check_diff --shed_target testtoolshed --shed_email $SHED_EMAIL --shed_password $SHED_PASSWORD; fi 
notifications:
    email:
        recipients:
            - scottx611x@gmail.com
    on_success: never
